"""
The ground-truth test, measured — D0(b) test 1.

WHY THIS FILE EXISTS
    D0(b) test 1 asks "what will tell this loop it is wrong, and HOW FAST?", and the answer is
    a table of numbers. The brief is explicit that "figures in your report are measurements you
    ran, not numbers a model produced for you" (section 6, condition 2), so the table in
    docs/D0-why-an-agent.md is generated by running this, not by typing plausible microseconds.

    Run it and paste the output. It needs no key and no network.

        cd src && python3 bench_ground_truth.py

WHAT IT MEASURES
    Median wall-clock of one keyed read per system of record, over N repeats, plus the one-off
    cost of loading all eight fixture files at import. The comparison that matters is against a
    model call of one to three seconds — that is the ratio D0 argues from, and it is so large
    that the exact microsecond does not change the conclusion. We report the microsecond anyway
    because an unmeasured number in a table is a number a marker is entitled to disbelieve.

THE ONE HONEST CAVEAT, AND IT IS IN THE OUTPUT
    check_claim_history is the only tool that is not a keyed lookup. It scans decided_claims
    linearly, so its cost grows with the evaluation set — the case baton (PLAN.md §3) takes
    that table from 4 rows towards ~60. The number below is therefore a snapshot, and the row
    prints the row count beside it so the table can never quietly go stale.

Owner: ZHENG YONGJIE (D0). Written against the tool layer in tools.py.
"""

from __future__ import annotations

import json
import os
import platform
import statistics
import sys
import time
import timeit

import tools

REPEATS = 2000

# One representative call per system of record. Ids are real rows from data_A, and each one is
# the row that D0 cites as the contradiction that system can deliver.
PROBES = [
    ("claims.json", "get_claim",
     'tools.get_claim("CLM-8842")'),
    ("policies.json", "lookup_policy",
     'tools.lookup_policy("M-2214", "2026-09-02")'),
    ("procedures + exclusions + required_documents", "check_coverage",
     'tools.check_coverage("POL-3310", "31255")'),
    ("preauthorisations.json", "get_preauthorisation",
     'tools.get_preauthorisation("M-6118", "29881", "2026-06-14")'),
    ("hospitals.json", "get_hospital_status",
     'tools.get_hospital_status("H-330")'),
    ("decided_claims.json", "check_claim_history",
     'tools.check_claim_history("M-2214", "H-114", "2026-08-20",'
     ' [{"code": "47120", "amount": 1400}])'),
]

FIXTURES = ["claims", "members", "policies", "procedures", "hospitals",
            "preauthorisations", "required_documents", "decided_claims"]


def _median_us(stmt: str, repeats: int = REPEATS) -> float:
    samples = timeit.repeat(stmt, globals={"tools": tools}, number=1, repeat=repeats)
    return statistics.median(samples) * 1e6


def _startup_ms(repeats: int = 200) -> float:
    """Cost of loading all eight fixture files once, at import. Paid per process, not per call."""
    data_dir = tools._DATA
    samples = []
    for _ in range(repeats):
        t0 = time.perf_counter()
        for name in FIXTURES:
            with open(os.path.join(data_dir, name + ".json"), encoding="utf-8") as fh:
                json.load(fh)
        samples.append(time.perf_counter() - t0)
    return statistics.median(samples) * 1000


def main() -> None:
    print(f"machine   {platform.machine()} · {platform.system()} · "
          f"Python {sys.version.split()[0]}")
    print(f"method    median of {REPEATS} calls each, wall clock, warm process")
    print(f"date      {time.strftime('%Y-%m-%d')}")
    print()
    print(f"{'system of record':<46} {'tool':<22} {'median':>10}")
    print("-" * 80)
    for record, tool, stmt in PROBES:
        print(f"{record:<46} {tool:<22} {_median_us(stmt):>7.2f} us")
    print("-" * 80)
    print(f"{'load all 8 fixture files (once, at import)':<46} "
          f"{'':<22} {_startup_ms():>7.3f} ms")
    print()
    print(f"decided_claims.json currently holds {len(tools._DECIDED)} rows. "
          f"check_claim_history scans them linearly,")
    print("so re-run this after the case baton (PLAN.md §3) — that row is the only one that "
          "grows.")
    print()
    print("Compare against one model call: 1-3 s. Ground truth is roughly six orders of "
          "magnitude cheaper")
    print("than the reasoning it corrects, which is what lets the loop iterate without a human "
          "in each turn.")


if __name__ == "__main__":
    main()
